baseline_nst:
  image_size: 256
  style_weight: 1000000.0
  steps: 150
  device: null

training:
  epochs: 18
  batch_size: 1
  learning_rate: 0.0002
  fast_dev_run: False
  gen_name: "unet"
  num_resblocks: 6
  hid_channels: 64
  lambda_idt: 0.5
  lambda_cycle: [10.0, 10.0]
  buffer_size: 100
  decay_epochs: 18
